export const COUNTRY_CODES = [
  { code: "+93", country: "Afghanistan", value: "+93-AF" },
  { code: "+355", country: "Albania", value: "+355-AL" },
  { code: "+54", country: "Argentina", value: "+54-AR" },
  { code: "+61", country: "Australia", value: "+61-AU" },
  { code: "+43", country: "Austria", value: "+43-AT" },
  { code: "+973", country: "Bahrain", value: "+973-BH" },
  { code: "+880", country: "Bangladesh", value: "+880-BD" },
  { code: "+32", country: "Belgium", value: "+32-BE" },
  { code: "+55", country: "Brazil", value: "+55-BR" },
  { code: "+359", country: "Bulgaria", value: "+359-BG" },
  { code: "+855", country: "Cambodia", value: "+855-KH" },
  { code: "+237", country: "Cameroon", value: "+237-CM" },
  { code: "+1", country: "Canada", value: "+1-CA" },
  { code: "+56", country: "Chile", value: "+56-CL" },
  { code: "+86", country: "China", value: "+86-CN" },
  { code: "+57", country: "Colombia", value: "+57-CO" },
  { code: "+385", country: "Croatia", value: "+385-HR" },
  { code: "+357", country: "Cyprus", value: "+357-CY" },
  { code: "+420", country: "Czech Republic", value: "+420-CZ" },
  { code: "+45", country: "Denmark", value: "+45-DK" },
  { code: "+20", country: "Egypt", value: "+20-EG" },
  { code: "+372", country: "Estonia", value: "+372-EE" },
  { code: "+251", country: "Ethiopia", value: "+251-ET" },
  { code: "+358", country: "Finland", value: "+358-FI" },
  { code: "+33", country: "France", value: "+33-FR" },
  { code: "+49", country: "Germany", value: "+49-DE" },
  { code: "+233", country: "Ghana", value: "+233-GH" },
  { code: "+30", country: "Greece", value: "+30-GR" },
  { code: "+852", country: "Hong Kong", value: "+852-HK" },
  { code: "+36", country: "Hungary", value: "+36-HU" },
  { code: "+354", country: "Iceland", value: "+354-IS" },
  { code: "+91", country: "India", value: "+91-IN" },
  { code: "+62", country: "Indonesia", value: "+62-ID" },
  { code: "+98", country: "Iran", value: "+98-IR" },
  { code: "+964", country: "Iraq", value: "+964-IQ" },
  { code: "+353", country: "Ireland", value: "+353-IE" },
  { code: "+972", country: "Israel", value: "+972-IL" },
  { code: "+39", country: "Italy", value: "+39-IT" },
  { code: "+81", country: "Japan", value: "+81-JP" },
  { code: "+962", country: "Jordan", value: "+962-JO" },
  { code: "+7", country: "Kazakhstan", value: "+7-KZ" },
  { code: "+254", country: "Kenya", value: "+254-KE" },
  { code: "+965", country: "Kuwait", value: "+965-KW" },
  { code: "+856", country: "Laos", value: "+856-LA" },
  { code: "+371", country: "Latvia", value: "+371-LV" },
  { code: "+961", country: "Lebanon", value: "+961-LB" },
  { code: "+370", country: "Lithuania", value: "+370-LT" },
  { code: "+352", country: "Luxembourg", value: "+352-LU" },
  { code: "+853", country: "Macau", value: "+853-MO" },
  { code: "+60", country: "Malaysia", value: "+60-MY" },
  { code: "+960", country: "Maldives", value: "+960-MV" },
  { code: "+52", country: "Mexico", value: "+52-MX" },
  { code: "+976", country: "Mongolia", value: "+976-MN" },
  { code: "+212", country: "Morocco", value: "+212-MA" },
  { code: "+95", country: "Myanmar", value: "+95-MM" },
  { code: "+977", country: "Nepal", value: "+977-NP" },
  { code: "+31", country: "Netherlands", value: "+31-NL" },
  { code: "+64", country: "New Zealand", value: "+64-NZ" },
  { code: "+234", country: "Nigeria", value: "+234-NG" },
  { code: "+47", country: "Norway", value: "+47-NO" },
  { code: "+968", country: "Oman", value: "+968-OM" },
  { code: "+92", country: "Pakistan", value: "+92-PK" },
  { code: "+507", country: "Panama", value: "+507-PA" },
  { code: "+51", country: "Peru", value: "+51-PE" },
  { code: "+63", country: "Philippines", value: "+63-PH" },
  { code: "+48", country: "Poland", value: "+48-PL" },
  { code: "+351", country: "Portugal", value: "+351-PT" },
  { code: "+974", country: "Qatar", value: "+974-QA" },
  { code: "+40", country: "Romania", value: "+40-RO" },
  { code: "+7", country: "Russia", value: "+7-RU" },
  { code: "+966", country: "Saudi Arabia", value: "+966-SA" },
  { code: "+381", country: "Serbia", value: "+381-RS" },
  { code: "+65", country: "Singapore", value: "+65-SG" },
  { code: "+421", country: "Slovakia", value: "+421-SK" },
  { code: "+386", country: "Slovenia", value: "+386-SI" },
  { code: "+27", country: "South Africa", value: "+27-ZA" },
  { code: "+82", country: "South Korea", value: "+82-KR" },
  { code: "+34", country: "Spain", value: "+34-ES" },
  { code: "+94", country: "Sri Lanka", value: "+94-LK" },
  { code: "+46", country: "Sweden", value: "+46-SE" },
  { code: "+41", country: "Switzerland", value: "+41-CH" },
  { code: "+886", country: "Taiwan", value: "+886-TW" },
  { code: "+255", country: "Tanzania", value: "+255-TZ" },
  { code: "+66", country: "Thailand", value: "+66-TH" },
  { code: "+90", country: "Turkey", value: "+90-TR" },
  { code: "+256", country: "Uganda", value: "+256-UG" },
  { code: "+380", country: "Ukraine", value: "+380-UA" },
  { code: "+971", country: "UAE", value: "+971-AE" },
  { code: "+44", country: "UK", value: "+44-GB" },
  { code: "+1", country: "USA", value: "+1-US" },
  { code: "+998", country: "Uzbekistan", value: "+998-UZ" },
  { code: "+84", country: "Vietnam", value: "+84-VN" },
];

export function getCodeFromValue(value: string): string {
  const entry = COUNTRY_CODES.find((cc) => cc.value === value);
  return entry?.code || value;
}

export const DEFAULT_COUNTRY_VALUE = "+66-TH";
